-- ============================================================
-- FILE: 01_foreign_keys.sql
-- DESC: Tạo toàn bộ ràng buộc khóa ngoại
-- NOTE: Chạy SAU 00_create_tables.sql
-- ============================================================

-- TAIKHOAN → NHOM
ALTER TABLE "TAIKHOAN" ADD CONSTRAINT "FK_TK_NHOM"
  FOREIGN KEY ("MANHOM") REFERENCES "NHOM" ("MANHOM");

-- NHANVIEN → TAIKHOAN
ALTER TABLE "NHANVIEN" ADD CONSTRAINT "FK_NV_TK"
  FOREIGN KEY ("MATK") REFERENCES "TAIKHOAN" ("MATK");

-- NHANVIEN → CUAHANG
ALTER TABLE "NHANVIEN" ADD CONSTRAINT "FK_NV_CH"
  FOREIGN KEY ("MACH") REFERENCES "CUAHANG" ("MACH");

-- DANHMUCSANPHAM → DANHMUCSANPHAM (self-reference)
ALTER TABLE "DANHMUCSANPHAM" ADD CONSTRAINT "FK_DM_CHA"
  FOREIGN KEY ("MADM_CHA") REFERENCES "DANHMUCSANPHAM" ("MADM");

-- SANPHAM → DANHMUCSANPHAM
ALTER TABLE "SANPHAM" ADD CONSTRAINT "FK_SP_DM"
  FOREIGN KEY ("MADM") REFERENCES "DANHMUCSANPHAM" ("MADM");

-- BIENTHE → SANPHAM
ALTER TABLE "BIENTHE" ADD CONSTRAINT "FK_BT_SP"
  FOREIGN KEY ("MASP") REFERENCES "SANPHAM" ("MASP");

-- SERIALNUMBER → BIENTHE
ALTER TABLE "SERIALNUMBER" ADD CONSTRAINT "FK_SN_BT"
  FOREIGN KEY ("MABIENTHE") REFERENCES "BIENTHE" ("MABIENTHE");

-- SERIALNUMBER → CUAHANG
ALTER TABLE "SERIALNUMBER" ADD CONSTRAINT "FK_SN_CH"
  FOREIGN KEY ("MACH") REFERENCES "CUAHANG" ("MACH");

-- TONKHO → CUAHANG
ALTER TABLE "TONKHO" ADD CONSTRAINT "FK_TK_CH"
  FOREIGN KEY ("MACH") REFERENCES "CUAHANG" ("MACH");

-- TONKHO → BIENTHE
ALTER TABLE "TONKHO" ADD CONSTRAINT "FK_TK_BT"
  FOREIGN KEY ("MABIENTHE") REFERENCES "BIENTHE" ("MABIENTHE");

-- PHIEUNHAP → CUAHANG
ALTER TABLE "PHIEUNHAP" ADD CONSTRAINT "FK_PN_CH"
  FOREIGN KEY ("MACH") REFERENCES "CUAHANG" ("MACH");

-- PHIEUNHAP → NHACUNGCAP
ALTER TABLE "PHIEUNHAP" ADD CONSTRAINT "FK_PN_NCC"
  FOREIGN KEY ("MANCC") REFERENCES "NHACUNGCAP" ("MANCC");

-- PHIEUNHAP → NHANVIEN
ALTER TABLE "PHIEUNHAP" ADD CONSTRAINT "FK_PN_NV"
  FOREIGN KEY ("MANV") REFERENCES "NHANVIEN" ("MANV");

-- CHITIETPHIEUNHAP → PHIEUNHAP
ALTER TABLE "CHITIETPHIEUNHAP" ADD CONSTRAINT "FK_CTPN_PN"
  FOREIGN KEY ("MAPN") REFERENCES "PHIEUNHAP" ("MAPN");

-- CHITIETPHIEUNHAP → BIENTHE
ALTER TABLE "CHITIETPHIEUNHAP" ADD CONSTRAINT "FK_CTPN_BT"
  FOREIGN KEY ("MABIENTHE") REFERENCES "BIENTHE" ("MABIENTHE");

-- PHIEUCHUYENKHO → CUAHANG (nguồn)
ALTER TABLE "PHIEUCHUYENKHO" ADD CONSTRAINT "FK_PCK_CH_NGUON"
  FOREIGN KEY ("MACH_NGUON") REFERENCES "CUAHANG" ("MACH");

-- PHIEUCHUYENKHO → CUAHANG (đích)
ALTER TABLE "PHIEUCHUYENKHO" ADD CONSTRAINT "FK_PCK_CH_DICH"
  FOREIGN KEY ("MACH_DICH") REFERENCES "CUAHANG" ("MACH");

-- PHIEUCHUYENKHO → NHANVIEN
ALTER TABLE "PHIEUCHUYENKHO" ADD CONSTRAINT "FK_PCK_NV"
  FOREIGN KEY ("MANV") REFERENCES "NHANVIEN" ("MANV");

-- CHITIETPHIEUCHUYENKHO → PHIEUCHUYENKHO
ALTER TABLE "CHITIETPHIEUCHUYENKHO" ADD CONSTRAINT "FK_CTPCK_PCK"
  FOREIGN KEY ("MAPCK") REFERENCES "PHIEUCHUYENKHO" ("MAPCK");

-- CHITIETPHIEUCHUYENKHO → BIENTHE
ALTER TABLE "CHITIETPHIEUCHUYENKHO" ADD CONSTRAINT "FK_CTPCK_BT"
  FOREIGN KEY ("MABIENTHE") REFERENCES "BIENTHE" ("MABIENTHE");

-- DIACHIGIAOHANG → KHACHHANG
ALTER TABLE "DIACHIGIAOHANG" ADD CONSTRAINT "FK_DCGH_KH"
  FOREIGN KEY ("MAKH") REFERENCES "KHACHHANG" ("MAKH");

-- HOADON → CUAHANG
ALTER TABLE "HOADON" ADD CONSTRAINT "FK_HD_CH"
  FOREIGN KEY ("MACH") REFERENCES "CUAHANG" ("MACH");

-- HOADON → NHANVIEN
ALTER TABLE "HOADON" ADD CONSTRAINT "FK_HD_NV"
  FOREIGN KEY ("MANV") REFERENCES "NHANVIEN" ("MANV");

-- HOADON → KHACHHANG
ALTER TABLE "HOADON" ADD CONSTRAINT "FK_HD_KH"
  FOREIGN KEY ("MAKH") REFERENCES "KHACHHANG" ("MAKH");

-- HOADON → DIACHIGIAOHANG
ALTER TABLE "HOADON" ADD CONSTRAINT "FK_HD_DCGH"
  FOREIGN KEY ("MADCGH") REFERENCES "DIACHIGIAOHANG" ("MADCGH");

-- HOADON → VOUCHER
ALTER TABLE "HOADON" ADD CONSTRAINT "FK_HD_VOUCHER"
  FOREIGN KEY ("MAVOUCHER") REFERENCES "VOUCHER" ("MAVOUCHER");

-- CHITIETHOADON → HOADON
ALTER TABLE "CHITIETHOADON" ADD CONSTRAINT "FK_CTHD_HD"
  FOREIGN KEY ("MAHD") REFERENCES "HOADON" ("MAHD");

-- CHITIETHOADON → SERIALNUMBER
ALTER TABLE "CHITIETHOADON" ADD CONSTRAINT "FK_CTHD_SN"
  FOREIGN KEY ("MASN") REFERENCES "SERIALNUMBER" ("MASN");

-- VANCHUYEN → HOADON
ALTER TABLE "VANCHUYEN" ADD CONSTRAINT "FK_VC_HD"
  FOREIGN KEY ("MAHD") REFERENCES "HOADON" ("MAHD");

PROMPT === 01_foreign_keys.sql: Tao khoa ngoai hoan tat ===